import type { FormsProfile } from "./module.js";

export const b2cFormsProfile: FormsProfile = {
  key: "b2c-forms",
  audience: "b2c",
  description: "Public contact, application and appointment forms.",
  capabilities: [
    "forms",
    "multi-step",
    "drafts",
    "file-uploads",
    "spam-protection",
    "consents",
    "notifications",
    "retention",
    "exports",
  ],
  requiredProviders: [
    "definitions",
    "validation",
    "files",
    "spam",
    "consents",
    "submissions",
    "workflows",
    "notifications",
    "retention",
    "events",
  ],
  settings: {
    authentication: "optional",
    defaultWorkflow: "simple",
    allowDrafts: true,
    requireConsent: true,
    requireSignature: false,
  },
};

export const b2bFormsProfile: FormsProfile = {
  key: "b2b-forms",
  audience: "b2b",
  description: "Lead, quote request and partner onboarding workflows.",
  capabilities: [
    "forms",
    "multi-step",
    "drafts",
    "file-uploads",
    "consents",
    "workflows",
    "tasks",
    "notifications",
    "retention",
    "exports",
    "crm",
    "erp",
  ],
  requiredProviders: [
    "definitions",
    "validation",
    "files",
    "consents",
    "submissions",
    "workflows",
    "tasks",
    "notifications",
    "retention",
    "integrations",
    "events",
  ],
  settings: {
    authentication: "organization",
    defaultWorkflow: "review",
    allowDrafts: true,
    requireConsent: true,
    requireSignature: false,
  },
};

export const b2gFormsProfile: FormsProfile = {
  key: "b2g-forms",
  audience: "b2g",
  description: "Formal applications with signature, case workflow and records export.",
  capabilities: [
    "forms",
    "multi-step",
    "drafts",
    "file-uploads",
    "consents",
    "signatures",
    "workflows",
    "tasks",
    "notifications",
    "retention",
    "exports",
    "dms",
    "case-management",
    "formal-applications",
    "xfall",
  ],
  requiredProviders: [
    "definitions",
    "validation",
    "files",
    "consents",
    "signatures",
    "submissions",
    "workflows",
    "tasks",
    "notifications",
    "retention",
    "exports",
    "integrations",
    "events",
  ],
  settings: {
    authentication: "required",
    defaultWorkflow: "formal",
    allowDrafts: true,
    requireConsent: true,
    requireSignature: true,
  },
};

export const formsProfiles = {
  b2c: b2cFormsProfile,
  b2b: b2bFormsProfile,
  b2g: b2gFormsProfile,
} as const;
