import type { CommerceProfile } from "./module.js";

export const b2cProfile: CommerceProfile = {
  key: "b2c-default",
  audience: "b2c",
  description: "Public prices, guest or account checkout, payment and fulfillment.",
  capabilities: [
    "catalog",
    "pricing",
    "inventory",
    "cart",
    "checkout",
    "guest-checkout",
    "payments",
    "shipping",
    "tax",
    "discounts",
    "customer-accounts",
    "returns",
  ],
  requiredProviders: [
    "catalog",
    "pricing",
    "inventory",
    "carts",
    "checkout",
    "orders",
    "payments",
    "tax",
    "fulfillment",
    "events",
  ],
  settings: {
    checkoutMode: "direct",
    customerMode: "guest_or_account",
    pricingMode: "public",
    taxDisplay: "gross",
    paymentRequired: true,
  },
};

export const b2bProfile: CommerceProfile = {
  key: "b2b-default",
  audience: "b2b",
  description: "Organization accounts, customer pricing, quotes and purchase orders.",
  capabilities: [
    "catalog",
    "pricing",
    "contract-pricing",
    "inventory",
    "cart",
    "checkout",
    "customer-accounts",
    "organization-accounts",
    "quotes",
    "approvals",
    "cost-centers",
    "purchase-orders",
    "invoicing",
    "erp",
  ],
  requiredProviders: [
    "catalog",
    "pricing",
    "inventory",
    "customers",
    "carts",
    "checkout",
    "orders",
    "quotes",
    "invoicing",
    "events",
  ],
  settings: {
    checkoutMode: "quote",
    customerMode: "organization",
    pricingMode: "customer",
    taxDisplay: "net",
    paymentRequired: false,
  },
};

export const b2gProfile: CommerceProfile = {
  key: "b2g-default",
  audience: "b2g",
  description: "Contract pricing, formal approvals, budgets and electronic invoicing.",
  capabilities: [
    "catalog",
    "pricing",
    "contract-pricing",
    "inventory",
    "cart",
    "checkout",
    "organization-accounts",
    "contracts",
    "quotes",
    "approvals",
    "budgets",
    "cost-centers",
    "purchase-orders",
    "invoicing",
    "xrechnung",
    "zugferd",
    "erp",
  ],
  requiredProviders: [
    "catalog",
    "pricing",
    "inventory",
    "customers",
    "carts",
    "checkout",
    "orders",
    "contracts",
    "budgets",
    "approvals",
    "quotes",
    "invoicing",
    "events",
  ],
  settings: {
    checkoutMode: "approval",
    customerMode: "organization",
    pricingMode: "contract",
    taxDisplay: "net",
    paymentRequired: false,
  },
};

export const commerceProfiles = {
  b2c: b2cProfile,
  b2b: b2bProfile,
  b2g: b2gProfile,
} as const;
