//! Kubernetes resource builders for managed PostgreSQL data stores (O3.1).
//!
//! Pure, deterministic functions: given a `SiteGraphDataStore`, its resolved
//! `StorageProfileSpec` and generated credentials, they produce the desired
//! Kubernetes objects (Secret, ConfigMap, headless Service, single-instance
//! StatefulSet with a PVC template, and an idempotent bootstrap Job).
//!
//! No cluster interaction and no secret values in non-Secret objects. The
//! reconciler (O3.2) applies these with server-side apply and owner references.
//! O3 is explicitly single-instance; HA is O7.

use k8s_openapi::api::apps::v1::{StatefulSet, StatefulSetSpec};
use k8s_openapi::api::batch::v1::{Job, JobSpec};
use k8s_openapi::api::core::v1::{
    ConfigMap, ConfigMapVolumeSource, Container, ContainerPort, EnvVar, EnvVarSource, ExecAction,
    PersistentVolumeClaim, PersistentVolumeClaimSpec, PodSecurityContext, PodSpec, PodTemplateSpec,
    Probe, ResourceRequirements, Secret, SecretKeySelector, Service, ServicePort, ServiceSpec,
    Volume, VolumeMount, VolumeResourceRequirements,
};
use k8s_openapi::apimachinery::pkg::api::resource::Quantity;
use k8s_openapi::apimachinery::pkg::apis::meta::v1::{LabelSelector, ObjectMeta, OwnerReference};
use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
use sitegraph_operator_api::{SiteGraphDataStore, StorageProfileSpec, API_GROUP, API_VERSION};
use std::collections::BTreeMap;

const MANAGED_BY: &str = "sitegraph-storage-operator";
const PVC_TEMPLATE_NAME: &str = "data";
const POSTGRES_PORT: i32 = 5432;
const DATA_MOUNT: &str = "/var/lib/postgresql/data";

/// Credentials generated by the operator at provisioning time. Plaintext lives
/// only inside the generated Kubernetes Secret, never in CRD spec/status.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedCredentials {
    pub username: String,
    pub password: String,
    pub database: String,
}

/// Generate credentials for a managed store. The password is random; the
/// database name is a deterministic, sanitized identifier so re-runs are stable.
/// Called only when no credentials Secret exists yet (get-or-create), so a
/// restart never rotates an existing password.
pub fn generate_credentials(ds: &SiteGraphDataStore) -> GeneratedCredentials {
    use rand::RngCore;
    let mut bytes = [0u8; 24];
    rand::rngs::OsRng.fill_bytes(&mut bytes);
    let password = bytes.iter().map(|b| format!("{b:02x}")).collect::<String>();
    let database = sanitize_identifier(&format!(
        "{}_{}_{}",
        ds.spec.organization_id, ds.spec.domain, ds.spec.data_category
    ));
    GeneratedCredentials {
        username: "sitegraph".to_string(),
        password,
        database,
    }
}

/// Lowercase, replace non-alphanumeric with `_`, ensure it starts with a letter.
fn sanitize_identifier(raw: &str) -> String {
    let mut out: String = raw
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    if !out.chars().next().is_some_and(|c| c.is_ascii_alphabetic()) {
        out.insert(0, 'd');
    }
    out.truncate(63);
    out
}

/// The full desired set of Kubernetes objects for one managed data store.
#[derive(Debug, Clone, PartialEq)]
pub struct DataStoreResources {
    pub secret: Secret,
    pub config_map: ConfigMap,
    pub service: Service,
    pub stateful_set: StatefulSet,
    pub bootstrap_job: Job,
}

// --- Naming ----------------------------------------------------------------

pub fn secret_name(base: &str) -> String {
    format!("{base}-credentials")
}
pub fn config_map_name(base: &str) -> String {
    format!("{base}-config")
}
pub fn service_name(base: &str) -> String {
    format!("{base}-db")
}
pub fn stateful_set_name(base: &str) -> String {
    base.to_string()
}
pub fn bootstrap_job_name(base: &str, generation: i64) -> String {
    // Generation in the name makes a re-bootstrap after a spec change a new,
    // immutable Job instead of an illegal in-place mutation.
    format!("{base}-bootstrap-{generation}")
}

// --- Labels / selector / owner ---------------------------------------------

/// Stable selector labels (must never change for a given store).
pub fn selector_labels(base: &str) -> BTreeMap<String, String> {
    BTreeMap::from([
        ("app.kubernetes.io/name".to_string(), "sitegraph-datastore".to_string()),
        ("app.kubernetes.io/instance".to_string(), base.to_string()),
    ])
}

/// Full label set including managed-by and routing dimensions (no secrets).
pub fn common_labels(ds: &SiteGraphDataStore, base: &str) -> BTreeMap<String, String> {
    let mut labels = selector_labels(base);
    labels.insert("app.kubernetes.io/managed-by".to_string(), MANAGED_BY.to_string());
    labels.insert(
        "platform.sitegraph.io/organization".to_string(),
        ds.spec.organization_id.clone(),
    );
    labels.insert("platform.sitegraph.io/domain".to_string(), ds.spec.domain.clone());
    labels.insert(
        "platform.sitegraph.io/data-category".to_string(),
        ds.spec.data_category.clone(),
    );
    labels.insert("platform.sitegraph.io/region".to_string(), ds.spec.region.clone());
    labels
}

/// Controller owner reference so children are garbage-collected with the store.
pub fn owner_reference(ds: &SiteGraphDataStore) -> OwnerReference {
    OwnerReference {
        api_version: format!("{API_GROUP}/{API_VERSION}"),
        kind: "SiteGraphDataStore".to_string(),
        name: ds.metadata.name.clone().unwrap_or_default(),
        uid: ds.metadata.uid.clone().unwrap_or_default(),
        controller: Some(true),
        block_owner_deletion: Some(true),
    }
}

fn object_meta(ds: &SiteGraphDataStore, name: String, labels: BTreeMap<String, String>) -> ObjectMeta {
    ObjectMeta {
        name: Some(name),
        namespace: ds.metadata.namespace.clone(),
        labels: Some(labels),
        owner_references: Some(vec![owner_reference(ds)]),
        ..Default::default()
    }
}

fn quantity_map(values: &BTreeMap<String, String>) -> Option<BTreeMap<String, Quantity>> {
    if values.is_empty() {
        return None;
    }
    Some(values.iter().map(|(k, v)| (k.clone(), Quantity(v.clone()))).collect())
}

// --- Builders --------------------------------------------------------------

/// Opaque credentials Secret. A rotation annotation lets a future rotation
/// trigger a controlled restart without changing the Secret's identity.
pub fn build_credentials_secret(
    ds: &SiteGraphDataStore,
    base: &str,
    creds: &GeneratedCredentials,
) -> Secret {
    let generation = ds.metadata.generation.unwrap_or_default();
    let mut meta = object_meta(ds, secret_name(base), common_labels(ds, base));
    meta.annotations = Some(BTreeMap::from([(
        "platform.sitegraph.io/rotation-generation".to_string(),
        generation.to_string(),
    )]));
    Secret {
        metadata: meta,
        type_: Some("Opaque".to_string()),
        string_data: Some(BTreeMap::from([
            ("username".to_string(), creds.username.clone()),
            ("password".to_string(), creds.password.clone()),
            ("database".to_string(), creds.database.clone()),
        ])),
        ..Default::default()
    }
}

/// ConfigMap holding the idempotent bootstrap SQL (no credentials).
pub fn build_config_map(ds: &SiteGraphDataStore, base: &str) -> ConfigMap {
    let sql = "\
-- Idempotent bootstrap for a SiteGraph managed data store.\n\
CREATE SCHEMA IF NOT EXISTS app;\n\
DO $$\n\
BEGIN\n\
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app') THEN\n\
    CREATE ROLE app NOLOGIN;\n\
  END IF;\n\
END\n\
$$;\n\
GRANT USAGE ON SCHEMA app TO app;\n";
    ConfigMap {
        metadata: object_meta(ds, config_map_name(base), common_labels(ds, base)),
        data: Some(BTreeMap::from([("bootstrap.sql".to_string(), sql.to_string())])),
        ..Default::default()
    }
}

/// Headless Service fronting the StatefulSet pod.
pub fn build_service(ds: &SiteGraphDataStore, base: &str) -> Service {
    Service {
        metadata: object_meta(ds, service_name(base), common_labels(ds, base)),
        spec: Some(ServiceSpec {
            cluster_ip: Some("None".to_string()),
            selector: Some(selector_labels(base)),
            ports: Some(vec![ServicePort {
                name: Some("postgres".to_string()),
                port: POSTGRES_PORT,
                target_port: Some(IntOrString::Int(POSTGRES_PORT)),
                ..Default::default()
            }]),
            ..Default::default()
        }),
        ..Default::default()
    }
}

fn secret_env(name: &str, secret: &str, key: &str) -> EnvVar {
    EnvVar {
        name: name.to_string(),
        value_from: Some(EnvVarSource {
            secret_key_ref: Some(SecretKeySelector {
                name: secret.to_string(),
                key: key.to_string(),
                optional: Some(false),
            }),
            ..Default::default()
        }),
        ..Default::default()
    }
}

/// Single-instance StatefulSet with a PVC template (O3 is single-instance).
pub fn build_stateful_set(
    ds: &SiteGraphDataStore,
    base: &str,
    profile: &StorageProfileSpec,
) -> StatefulSet {
    let secret = secret_name(base);
    let labels = common_labels(ds, base);

    let container = Container {
        name: "postgres".to_string(),
        image: Some(profile.postgres.image.clone()),
        ports: Some(vec![ContainerPort {
            name: Some("postgres".to_string()),
            container_port: POSTGRES_PORT,
            ..Default::default()
        }]),
        env: Some(vec![
            secret_env("POSTGRES_USER", &secret, "username"),
            secret_env("POSTGRES_PASSWORD", &secret, "password"),
            secret_env("POSTGRES_DB", &secret, "database"),
            // Keep data in a subdirectory so the volume root may hold lost+found.
            EnvVar {
                name: "PGDATA".to_string(),
                value: Some(format!("{DATA_MOUNT}/pgdata")),
                ..Default::default()
            },
        ]),
        resources: Some(ResourceRequirements {
            requests: quantity_map(&profile.resources.requests),
            limits: quantity_map(&profile.resources.limits),
            ..Default::default()
        }),
        volume_mounts: Some(vec![VolumeMount {
            name: PVC_TEMPLATE_NAME.to_string(),
            mount_path: DATA_MOUNT.to_string(),
            ..Default::default()
        }]),
        readiness_probe: Some(pg_ready_probe(5, 5)),
        liveness_probe: Some(pg_ready_probe(15, 10)),
        ..Default::default()
    };

    let pod_spec = PodSpec {
        containers: vec![container],
        node_selector: (!profile.node_selector.is_empty()).then(|| profile.node_selector.clone()),
        security_context: Some(PodSecurityContext {
            // postgres official image runs as uid 999; fsGroup lets it write PVC.
            fs_group: Some(999),
            ..Default::default()
        }),
        ..Default::default()
    };

    let pvc = PersistentVolumeClaim {
        metadata: ObjectMeta {
            name: Some(PVC_TEMPLATE_NAME.to_string()),
            ..Default::default()
        },
        spec: Some(PersistentVolumeClaimSpec {
            access_modes: Some(vec!["ReadWriteOnce".to_string()]),
            storage_class_name: Some(profile.volume.storage_class_name.clone()),
            resources: Some(VolumeResourceRequirements {
                requests: Some(BTreeMap::from([(
                    "storage".to_string(),
                    Quantity(profile.volume.size.clone()),
                )])),
                ..Default::default()
            }),
            ..Default::default()
        }),
        ..Default::default()
    };

    StatefulSet {
        metadata: object_meta(ds, stateful_set_name(base), labels.clone()),
        spec: Some(StatefulSetSpec {
            replicas: Some(1),
            service_name: Some(service_name(base)),
            selector: LabelSelector {
                match_labels: Some(selector_labels(base)),
                ..Default::default()
            },
            template: PodTemplateSpec {
                metadata: Some(ObjectMeta {
                    labels: Some(labels),
                    ..Default::default()
                }),
                spec: Some(pod_spec),
            },
            volume_claim_templates: Some(vec![pvc]),
            ..Default::default()
        }),
        ..Default::default()
    }
}

fn pg_ready_probe(period: i32, initial: i32) -> Probe {
    Probe {
        exec: Some(ExecAction {
            command: Some(vec![
                "bash".to_string(),
                "-c".to_string(),
                "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\"".to_string(),
            ]),
        }),
        period_seconds: Some(period),
        initial_delay_seconds: Some(initial),
        ..Default::default()
    }
}

/// Idempotent bootstrap Job: waits for PostgreSQL, then applies bootstrap.sql.
pub fn build_bootstrap_job(
    ds: &SiteGraphDataStore,
    base: &str,
    profile: &StorageProfileSpec,
) -> Job {
    let generation = ds.metadata.generation.unwrap_or_default();
    let secret = secret_name(base);
    let config = config_map_name(base);
    let service = service_name(base);

    let script = format!(
        "set -euo pipefail\n\
         until pg_isready -h {service} -U \"$PGUSER\" -d \"$PGDATABASE\"; do sleep 2; done\n\
         psql -v ON_ERROR_STOP=1 -h {service} -f /sql/bootstrap.sql\n"
    );

    let container = Container {
        name: "bootstrap".to_string(),
        image: Some(profile.postgres.image.clone()),
        command: Some(vec!["bash".to_string(), "-c".to_string(), script]),
        env: Some(vec![
            EnvVar { name: "PGHOST".to_string(), value: Some(service.clone()), ..Default::default() },
            secret_env("PGUSER", &secret, "username"),
            secret_env("PGPASSWORD", &secret, "password"),
            secret_env("PGDATABASE", &secret, "database"),
        ]),
        volume_mounts: Some(vec![VolumeMount {
            name: "sql".to_string(),
            mount_path: "/sql".to_string(),
            read_only: Some(true),
            ..Default::default()
        }]),
        ..Default::default()
    };

    let pod_spec = PodSpec {
        containers: vec![container],
        restart_policy: Some("OnFailure".to_string()),
        volumes: Some(vec![Volume {
            name: "sql".to_string(),
            config_map: Some(ConfigMapVolumeSource {
                name: config,
                ..Default::default()
            }),
            ..Default::default()
        }]),
        ..Default::default()
    };

    Job {
        metadata: object_meta(ds, bootstrap_job_name(base, generation), common_labels(ds, base)),
        spec: Some(JobSpec {
            backoff_limit: Some(6),
            template: PodTemplateSpec {
                metadata: Some(ObjectMeta {
                    labels: Some(common_labels(ds, base)),
                    ..Default::default()
                }),
                spec: Some(pod_spec),
            },
            ..Default::default()
        }),
        ..Default::default()
    }
}

/// Build the full desired resource set for a managed data store.
pub fn build_data_store_resources(
    ds: &SiteGraphDataStore,
    base: &str,
    profile: &StorageProfileSpec,
    creds: &GeneratedCredentials,
) -> DataStoreResources {
    DataStoreResources {
        secret: build_credentials_secret(ds, base, creds),
        config_map: build_config_map(ds, base),
        service: build_service(ds, base),
        stateful_set: build_stateful_set(ds, base, profile),
        bootstrap_job: build_bootstrap_job(ds, base, profile),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sitegraph_operator_api::{
        DataStoreSpec, DeletionPolicy, IsolationTopology, PostgresRuntimeSpec, ResourceBudget,
        StorageVolumeSpec,
    };

    fn profile() -> StorageProfileSpec {
        StorageProfileSpec {
            postgres: PostgresRuntimeSpec { image: "postgres:17".into(), major_version: 17, replicas: 1 },
            volume: StorageVolumeSpec {
                storage_class_name: "standard".into(),
                size: "10Gi".into(),
                allow_expansion: true,
            },
            resources: ResourceBudget {
                requests: BTreeMap::from([("cpu".into(), "100m".into())]),
                limits: BTreeMap::from([("memory".into(), "512Mi".into())]),
            },
            node_selector: BTreeMap::new(),
            backup_profile_ref: None,
            tls_secret_ref: None,
            encryption_key_ref: None,
        }
    }

    fn data_store() -> SiteGraphDataStore {
        let mut ds = SiteGraphDataStore::new(
            "org-a-content",
            DataStoreSpec {
                organization_id: "org-a".into(),
                domain: "content".into(),
                data_category: "personal".into(),
                topology: IsolationTopology::DatabasePerTenant,
                region: "eu-central".into(),
                storage_profile_ref: Some("standard".into()),
                desired_schema_version: Some("1".into()),
                deletion_policy: DeletionPolicy::Retain,
                external: None,
            },
        );
        ds.metadata.namespace = Some("sitegraph-system".into());
        ds.metadata.uid = Some("uid-123".into());
        ds.metadata.generation = Some(2);
        ds
    }

    fn creds() -> GeneratedCredentials {
        GeneratedCredentials {
            username: "sitegraph".into(),
            password: "s3cr3t".into(),
            database: "org_a_content".into(),
        }
    }

    #[test]
    fn all_children_carry_controller_owner_reference() {
        let ds = data_store();
        let res = build_data_store_resources(&ds, "org-a-content", &profile(), &creds());
        for meta in [
            &res.secret.metadata,
            &res.config_map.metadata,
            &res.service.metadata,
            &res.stateful_set.metadata,
            &res.bootstrap_job.metadata,
        ] {
            let owner = &meta.owner_references.as_ref().unwrap()[0];
            assert_eq!(owner.kind, "SiteGraphDataStore");
            assert_eq!(owner.uid, "uid-123");
            assert_eq!(owner.controller, Some(true));
            assert_eq!(meta.namespace.as_deref(), Some("sitegraph-system"));
        }
    }

    #[test]
    fn stateful_set_is_single_instance_with_pvc_from_profile() {
        let ds = data_store();
        let sts = build_stateful_set(&ds, "org-a-content", &profile());
        let spec = sts.spec.unwrap();
        assert_eq!(spec.replicas, Some(1));
        assert_eq!(spec.service_name.as_deref(), Some("org-a-content-db"));
        let pvc = &spec.volume_claim_templates.unwrap()[0];
        let pvc_spec = pvc.spec.as_ref().unwrap();
        assert_eq!(pvc_spec.storage_class_name.as_deref(), Some("standard"));
        assert_eq!(
            pvc_spec.resources.as_ref().unwrap().requests.as_ref().unwrap()["storage"],
            Quantity("10Gi".into())
        );
        let container = &spec.template.spec.unwrap().containers[0];
        assert_eq!(container.image.as_deref(), Some("postgres:17"));
    }

    #[test]
    fn credentials_only_live_in_the_secret() {
        let ds = data_store();
        let res = build_data_store_resources(&ds, "org-a-content", &profile(), &creds());
        // Secret carries the plaintext via stringData.
        assert_eq!(res.secret.string_data.as_ref().unwrap()["password"], "s3cr3t");
        // No other object serializes the password.
        for object in [
            serde_json::to_string(&res.config_map).unwrap(),
            serde_json::to_string(&res.service).unwrap(),
            serde_json::to_string(&res.stateful_set).unwrap(),
            serde_json::to_string(&res.bootstrap_job).unwrap(),
        ] {
            assert!(!object.contains("s3cr3t"), "plaintext leaked into a non-secret object");
        }
    }

    #[test]
    fn workloads_consume_credentials_only_by_secret_reference() {
        let ds = data_store();
        let sts = build_stateful_set(&ds, "org-a-content", &profile());
        let env = sts.spec.unwrap().template.spec.unwrap().containers[0].env.clone().unwrap();
        let pw = env.iter().find(|e| e.name == "POSTGRES_PASSWORD").unwrap();
        assert!(pw.value.is_none());
        assert_eq!(
            pw.value_from.as_ref().unwrap().secret_key_ref.as_ref().unwrap().name,
            "org-a-content-credentials"
        );
    }

    #[test]
    fn service_is_headless_on_postgres_port() {
        let ds = data_store();
        let svc = build_service(&ds, "org-a-content");
        let spec = svc.spec.unwrap();
        assert_eq!(spec.cluster_ip.as_deref(), Some("None"));
        assert_eq!(spec.ports.unwrap()[0].port, 5432);
    }

    #[test]
    fn bootstrap_job_name_includes_generation_for_immutability() {
        let ds = data_store();
        let job = build_bootstrap_job(&ds, "org-a-content", &profile());
        assert_eq!(job.metadata.name.as_deref(), Some("org-a-content-bootstrap-2"));
        // OnFailure so a transient failure retries without recreating the Job.
        assert_eq!(
            job.spec.unwrap().template.spec.unwrap().restart_policy.as_deref(),
            Some("OnFailure")
        );
    }

    #[test]
    fn generated_credentials_are_stable_db_and_random_password() {
        let ds = data_store();
        let a = generate_credentials(&ds);
        let b = generate_credentials(&ds);
        assert_eq!(a.database, "org_a_content_personal");
        assert_eq!(a.username, "sitegraph");
        assert_eq!(a.database, b.database, "database name must be deterministic");
        assert_ne!(a.password, b.password, "password must be random");
        assert_eq!(a.password.len(), 48);
    }

    #[test]
    fn sanitize_identifier_forces_leading_letter() {
        assert_eq!(sanitize_identifier("123-abc"), "d123_abc");
        assert_eq!(sanitize_identifier("Org.A/Content"), "org_a_content");
    }

    #[test]
    fn selector_labels_are_stable_subset_of_common_labels() {
        let ds = data_store();
        let selector = selector_labels("org-a-content");
        let common = common_labels(&ds, "org-a-content");
        for (k, v) in &selector {
            assert_eq!(common.get(k), Some(v));
        }
        assert!(common.contains_key("platform.sitegraph.io/organization"));
    }
}
